### ISSUE TITLE
The 0.3.0 api seems to be missing the configuration

### ISSUE THREAD

**Issue by farcaller** [onelogin/terraform-provider-onelogin#105]
Resource `onelogin_apps` seems to be lacking the "configuration" field, making it impossible to actually configure any application. Am I missing something?

**Comment by Jmfwolf** [comment]
Thank you for point that out.
I made an error in the specification for the apps. I will correct that in the next release

**Comment by Jmfwolf** [comment]
The OpenAPI specification has been updated as well as the readme.
A signed fork has been uploaded to the [Terraform Registry](https://registry.terraform.io/providers/Jmfwolf/onelogin/latest)

**Comment by Jmfwolf** [comment]
I have been looking into the issue, this is the top priority for this repo. I will keep you updated

**Comment by Jmfwolf** [comment]
Please check out the recent release. User and App resources have been added. I will continue to work on the schemas to allow more resources to be accessed

**Comment by jmons** [comment]
The providor went live this morning on terraform , so users may need to limit the prividor because it is missing a large number of resources:
![Screenshot 2023-03-10 at 10 28 09](https://user-images.githubusercontent.com/459533/224307868-f99fc66d-ba55-4fb1-b345-5b82583b1aac.png)
![Screenshot 2023-03-10 at 10 28 02](https://user-images.githubusercontent.com/459533/224307874-bc4db211-364e-46ee-b3f5-7a58cb6b2f89.png)

**Comment by Jmfwolf** [comment]
I am working to have the remaining resources added: App rules, smart hooks, users, and mappings. 

The previous way of handling SAML apps and OIDC apps as different resources, has been combined into the onelogin_app resource.

API Authorizations was formerly known as auth_server.
