### ISSUE TITLE
Early preview for delegated admin support?

### ISSUE THREAD

**Issue by marcusvoss** [onelogin/terraform-provider-onelogin#46]
Hi,

as you have announced the delegated admin feature to be in preview, I was wondering if you have a "preview" version of the terraform provider available as well?

Thanks
Marcus

Links as references
https://onelogin.service-now.com/support?id=kb_article&sys_id=128c53b2db1f2050ca1c400e0b961989&kb_category=20880e84db738300d5505eea4b9619fb
https://developers.onelogin.com/api-docs/1/privileges/list-privileges

**Comment by dcaponi** [comment]
Hey @marcusvoss we don't have a preview version of this functionality at this time. I'm happy to update here once its implemented.

**Comment by dcaponi** [comment]
Sorry, clicked the wrong button 😅

**Comment by dcaponi** [comment]
@marcusvoss if you're feeling adventurous and want to have a play around, I have this working on a branch https://github.com/onelogin/terraform-provider-onelogin/pull/53

It should work if you look at the [example](https://github.com/onelogin/terraform-provider-onelogin/blob/b228457f0291ef81817cd6e70e5c006c1a5bf454/docs/resources/onelogin_privileges.md) and follow it. 

I need to add a few guard rails since there are some rules you need to follow that arent immediately apparent unless you have the [docs](https://developers.onelogin.com/api-docs/1/privileges/create-privilege) handy and I want to bake some of those in to the error checking for a nicer experience. Once those are done, it should be fully released later this week.

**Comment by dcaponi** [comment]
@marcusvoss I'm closing this since the new version shipped with support for this 2wk ago and I haven't heard back since. If there's an issue with it, please open a new issue with details about the support you need.
