### ISSUE TITLE
onelogin_auth_server not setting state correctly

### ISSUE THREAD

**Issue by ebarti** [onelogin/terraform-provider-onelogin#87]
The provider fails to correctly set the state for `onelogin_auth_server` resources.

The error is when updating the configuration [here](https://github.com/onelogin/terraform-provider-onelogin/blob/071ea939ace28d55ef0d0db0baa2905b815b7a8e/onelogin/resource_onelogin_auth_servers.go#L81):

```go
d.Set("configuration", authserverconfigurationschema.Flatten(*authServer.Configuration))
```

`configuration: '': source data must be an array or slice, got map`

**Comment by ebarti** [comment]
Additionally, this error does not surface as it is explicitally ignored by the provider

**Comment by ebarti** [comment]
I created a maintained fork of this repo and fixed this issue there. https://github.com/Glovo/terraform-provider-onelogin @ 0.2.1 https://registry.terraform.io/providers/Glovo/onelogin/0.2.1

**Comment by Jmfwolf** [comment]
With you maintaining your private fork and Onelogin changing to an OpenAPI based SDK system, I want to make sure your issue is resolved. Between your fork or the new Onelogin Provider (installable via the script in the [README](https://github.com/onelogin/terraform-provider-onelogin#provider-installation) Has your issue been resolved?
